name: ping test

on:
  schedule:
    - cron: "0 23 * * *"  # 6am WIB (UTC+7)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: echo "hey im here! $(date)"
